blog_app/urls.py
from django.urls import path
from . import views

app_name = "blog_app"
# Contails all urls for the blog app

urlpatterns = [

    path('write/', views.CreateBlog.as_view(), name="write"),
    path('blog_list/', views.BlogList.as_view(), name="blog_list"),
    path('blog_details/<slug>', views.blog_details, name="blog_details"),
    path('my_blogs/', views.MyBlogs.as_view(), name="my_blogs"),
    path('edit_blogs/<int:pk>', views.UpdateBlogs.as_view(), name="edit_blogs"),
    path('liked/<int:pk>', views.liked_blog, name="like"),
    path('unliked/<int:pk>', views.unlike_blog, name="unlike"),
    path("search/", views.search, name="search")
     ]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('', views.home, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# The database table for a single blog


class Blog(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_blog")
    blog_title = models.CharField(max_length=400, verbose_name="Put A Title")
    slug = models.SlugField(max_length=200, unique=True)
    blog_content = models.TextField(verbose_name="What's On Your Mind?")
    blog_image = models.ImageField(
        upload_to="blog_images", verbose_name="Image", null="True", blank=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date']

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(
            Blog, on_delete=models.CASCADE, related_name="blog_comment")
    user = models.ForeignKey(
                User, on_delete=models.CASCADE, related_name="user_comment")
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment


class Like(models.Model):
    blog = models.ForeignKey(
                Blog, on_delete=models.CASCADE, related_name="blog_like")
    user = models.ForeignKey(
                User, on_delete=models.CASCADE, related_name="user_like")

    def __str__(self):
        return self.user.username

blog_app/forms.py
from django import forms
from . import models


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('comment',)

blog_app/views.py
from django.http import request
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, ListView, TemplateView, UpdateView
from blog_app.models import Blog, Like
from blog_app.forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
# Create your views here.

# Contains all the blog of a particular user
class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = "blog_app/my_blogs.html"
    
# Class based views
# Function for creating a new blog
class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'blog_app/write_blog.html'
    fields = ("blog_title", "blog_content", "blog_image")

    def form_valid(self, form):
        # ID --- primary
        blog_obj = form.save(commit=False)
        blog_obj.user = self.request.user
        title = blog_obj.blog_title
        # Slug in the URL
        blog_obj.slug = title.replace(" ", "-")+"-" + str(uuid.uuid4())
        # print("Title : ", blog_obj.blog_title)
        blog_obj.save()
        return HttpResponseRedirect(reverse('home'))

# All the blogs
class BlogList (ListView):
    context_object_name = "blogs"
    model = Blog
    template_name = "blog_app/blog_list.html"

# On login view the blog details
@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    commentForm = CommentForm()
    reacted_blog = Like.objects.filter(blog=blog, user=request.user)
    print(reacted_blog)
    if reacted_blog:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        commentForm = CommentForm(request.POST)
        if commentForm.is_valid():
            commentInfo = commentForm.save(commit=False)
            commentInfo.user = request.user
            commentInfo.blog = blog
            commentInfo.save()
            return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug': slug}))
    return render(request, 'blog_app/blog_details.html', context={'blog': blog, 'form': commentForm, 'liked': liked})


@login_required
def liked_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        user_liked = Like(blog=blog, user=user)
        user_liked.save()

    return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug': blog.slug}))


@login_required
def unlike_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    user_disliked = Like.objects.filter(blog=blog, user=user)
    user_disliked.delete()
    return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug': blog.slug}))

# Class based views
# function for updating blogs
class UpdateBlogs(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = "blog_app/edit_blog.html"

    def get_success_url(self, **kwargs):
        return reverse_lazy('blog_app:blog_details', kwargs={'slug': self.object.slug})


def search(request):
    query = request.GET['query']
    blogs = Blog.objects.filter(blog_title__icontains=query)
    dict = {'blogs': blogs}
    return render(request, 'blog_app/search.html', context=dict)

templates/blog_app/blog_details.html
{% extends 'base.html' %}
<!-- loading crispy -->
{% load crispy_forms_tags %}
<!-- saasdasd -->
{% block intro %}{% endblock %}
<!-- Title Changing -->
{% block title %} {{ blog.blog_title }} {% endblock %}
<!-- Changing Content -->
{% block content %}
<!--for single blog-->
<div class="row">
  <div class="col sm-6">
    <h2 id="topic">{{ blog.blog_title }}</h2>
    <h4>Posted By : <a id="users" href="#">@{{ blog.user }}</a></h4>
    <h6><i>{{ blog.publish_date }}</i></h6>
    <h6><i>{{ blog.update_date }}</i></h6>
    <h6>
      {{ blog.blog_like.count }} Likes | {{ blog.blog_comment.count }} Comments
    </h6>
  </div>
  <div class="col sm-6">
    <img src="/media/{{ blog.blog_image }}" alt="" class="img-fluid" />
  </div>
</div>
<h2 class="fs-2">{{ blog.blog_content|linebreaks }}</h2>
<br />
<div>
  {% if not liked %}
  <a href="{% url 'blog_app:like' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
  </a>
  {% else %}
  <a href="{% url 'blog_app:unlike' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
  </a>
  {% endif %}
</div>
<br />
<div class="row">
  <div class="col-sm-6">
    <h3>Comments:</h3>
    <hr />
    {% for comments in blog.blog_comment.all %}
    <h5><a href="#">@{{comments.user}}</a> {{ comments.comment }}</h5>

    <h6>{{ comments.comment_date }}</h6>
    {% endfor %}
  </div>
  <div class="col-sm-6">
    <form method="POST">
      {{ form|crispy }} {% csrf_token %}
      <button type="submit" class="btn btn-success btn-sm">Submit</button>
    </form>
  </div>
</div>

{% endblock %}

templates/blog_app/blog_list.html
{% extends 'base.html' %}
<!--  Changing Title  -->
{% block title %} Blogs {% endblock %}
<!-- Changing Content -->
{% block content %}
<!--Loop  -->

{% for msg in messages %}
<div
  class="alert alert-primary alert-dismissible fade show"
  role="alert"
  id="liveAlert"
>
  <strong>{{ msg }}</strong>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %}
<!-- sadasda -->
{% if blogs %} {% for blog in blogs %}
<h2 id="topic">{{ blog.blog_title }}</h2>
<h6>{{ blog.publish_date }}</h6>
<div class="row mb-4">
  <div class="col-sm-6">
    {% if blog.blog_image %}
    <img
      src="/media/{{ blog.blog_image }}"
      alt="{{ blog.blog_title }}"
      title="{{ blog.blog_title }}"
      style="object-fit: cover; height: 300px; width: 75%"
    />
    {% else %}
    <div class="alert alert-info">No Image Posted!</div>
    {% endif %}
  </div>
  <div class="col-sm-6">
    <h4 class="lead">
      {{ blog.blog_content|linebreaks|truncatechars:500 }}
      <a id="read" href="{% url 'blog_app:blog_details' slug=blog.slug %}"
        >READ MORE</a
      >
    </h4>
    <h5>Posted By: <i>@{{ blog.user }}</i></h5>
    <h6>
      {{ blog.blog_like.count }} Likes | {{ blog.blog_comment.count }} Comments
    </h6>
  </div>
</div>
{% endfor %} {% else %}
<div class="alert alert-success" role="alert">
  <h3 class="alert-heading">No blogs posted yet</h3>

  <p class="mb-0"></p>
</div>
{% endif %}
<!-- Done -->
{% endblock %}

templates/blog_app/edit_blog.html
{% extends 'base.html' %}
<!-- sahdoiasdioj -->
{% load crispy_forms_tags %}
<!-- Title Change -->
{% block title %} Edit {% endblock %}
<!-- Content Change -->
{% block intro %}{% endblock %}
<!-- sadas -->
{% block content %} {% if blog.user == user %}
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }} {% csrf_token %}
  <button type="submit" class="btn btn-success btn-md">Update</button>
</form>
{% else %} {% endif %} {% endblock %}

templates/blog_app/my_blogs.html
{% extends 'base.html' %}
<!--  Changing Title  -->
{% block title %} Blogs {% endblock %}
<!-- Changing Content -->
{% block intro %}{% endblock %}
<!-- sadsadsa -->
{% block content %}
<!--Loop  -->

{% for blog in user.user_blog.all %}
<!-- looping through blogs -->
<h2 id="topic">{{ blog.blog_title }}</h2>
<h6>{{ blog.publish_date }}</h6>
<div class="row mb-4">
  <div class="col-sm-6">
    {% if blog.blog_image %}
    <img
      src="/media/{{ blog.blog_image }}"
      alt="{{ blog.blog_title }}"
      title="{{ blog.blog_title }}"
      class="img-fluid"
      style="object-fit: cover"
    />
    {% else %}
    <div class="alert alert-info">No Image Posted!</div>
    {% endif %}
  </div>
  <div class="col-sm-6">
    <h3 class="lead">
      {{ blog.blog_content|linebreaks|truncatechars:500 }}
      <a id="read" href="{% url 'blog_app:blog_details' slug=blog.slug %}"
        >READ MORE |
      </a>
      <a href="{% url 'blog_app:edit_blogs' pk=blog.pk %}">EDIT</a>
    </h3>
    <h5>Posted By: <a id="users" id="users" href="#"> @{{ blog.user }} </a></h5>
    <h6>
      {{ blog.blog_like.count }} Likes | {{ blog.blog_comment.count }} Comments
    </h6>
  </div>
</div>
{% endfor %}

<!-- Done -->
{% endblock %}

templates/blog_app/search.html
{% extends 'base.html' %}
<!--  Changing Title  -->
{% block title %} Blogs {% endblock %}
<!-- Changing Content -->
{% block intro %}{% endblock %}
<!-- sadsa -->
{% block content %}
<!--Loop  -->
{% if blogs %}
<!-- sdsadasd -->
{% for blog in blogs %}
<h2 id="topic">{{ blog.blog_title }}</h2>
<h6>{{ blog.publish_date }}</h6>
<div class="row mb-4">
  <div class="col-sm-6">
    {% if blog.blog_image %}
    <img
      src="/media/{{ blog.blog_image }}"
      alt="{{ blog.blog_title }}"
      title="{{ blog.blog_title }}"
      class="img-fluid"
      style="object-fit: cover; height: 300px; width: 75%"
    />
    {% else %}
    <div class="alert alert-info">No Image Posted!</div>
    {% endif %}
  </div>
  <div class="col-sm-6">
    <h3 class="lead">
      {{ blog.blog_content|linebreaks|truncatechars:500 }}
      <a id="read" href="{% url 'blog_app:blog_details' slug=blog.slug %}"
        >READ MORE</a
      >
    </h3>
    <h5>Posted By: <a id="users" href="#"> @{{ blog.user }} </a></h5>
    <h6>
      {{ blog.blog_like.count }} Likes | {{ blog.blog_comment.count }} Comments
    </h6>
  </div>
</div>
{% endfor %}
<!--sadasdas  -->
{% else %}
<div class="jumbotron jumbotron-fluid">
  <div class="alert alert-danger">Sorry, No Results Found</div>
  <p class="lead">
    Return To <a class="alert-link" href="{% url 'home' %}">Home Page</a>
  </p>
</div>
{% endif %}
<!-- sadasdas -->

<!-- Done -->
{% endblock %}

templates/blog_app/write_blog.html
{% extends 'base.html' %}
<!-- Loading Crispy Tag  -->
{% load crispy_forms_tags %}
<!-- Changing Title -->
{% block title %} Write Blogs {% endblock %}
<!-- sadsad -->
{% block intro %}{% endblock %}
<!-- changing content -->
{% block content %}

<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }}
  <button class="btn btn-success">Publish</button>
  {% csrf_token %}
</form>

{% endblock %}