blog_app/urls.py
from django.urls import path
from . import views

app_name = "blog_app"
# Contails all urls for the blog app

urlpatterns = [

    path('write/', views.CreateBlog.as_view(), name="write"),
    path('blog_list/', views.BlogList.as_view(), name="blog_list"),
    path('blog_details/<slug>', views.blog_details, name="blog_details"),
    path('my_blogs/', views.MyBlogs.as_view(), name="my_blogs"),
    path('edit_blogs/<int:pk>', views.UpdateBlogs.as_view(), name="edit_blogs"),
    path('liked/<int:pk>', views.liked_blog, name="like"),
    path('unliked/<int:pk>', views.unlike_blog, name="unlike"),
    path("search/", views.search, name="search")
     ]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('', views.home, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name = "login_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signUp, name="signup"),
    path('signin/', views.signIn, name="signin"),
    path('signout/', views.signOut, name='signout'),
    path('profile/', views.user_profile, name="profile"),
    path('change_info/', views.user_info_change, name="change_info"),
    path("password/", views.pass_change, name="pass_change"),
    path("add_pic/", views.add_pro_pic, name="add_pic"),
    path("change_pic/", views.change_pro_pic, name="change_pic"),

]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class userInfo(models.Model):
    user = models.OneToOneField(
        User, related_name="user_profile", on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

    def __str__(self):
        return self.user.username

login_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from .import models


class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'placeholder': 'abc@northsouth.edu'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2',)


class UserInfoChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class ProfilePicForm(forms.ModelForm):
    class Meta:
        model = models.userInfo
        fields = ('profile_pic',)

login_app/views.py
from typing import Counter
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponse
from .forms import SignUpForm, UserInfoChange, ProfilePicForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import re

# Create your views here.


def home(request):
    return render(request, 'blog_app/blog_list.html', context={})


def signUp(request):
    registered = False
    if request.method == "POST":
        signup = SignUpForm(data=request.POST)
        email_string = str(request.POST['email'])
        pattern = re.compile(r"^[a-z]*\.[a-z]*[0-9]*@northsouth.edu")
        matches = pattern.findall(email_string)
        if len(matches) == 0 or matches[0] == ".":
            messages.error(request, "Sorry, You cannot Use this Service")
            return render(request, 'login_app/error.html')
        else:
            if signup.is_valid():
                signup.save()
                registered = True
                messages.success(request, "Registration successful")
                return HttpResponseRedirect(reverse('login_app:signin'))
    else:
        signup = SignUpForm()

    dict = {'form': signup, 'registered': registered}
    return render(request, 'login_app/register.html', context=dict)


def signIn(request):
    success = False
    if request.method == "POST":
        signin = AuthenticationForm(data=request.POST)
        if signin.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                success = True
                messages.success(request, "You are logged in")
                return HttpResponseRedirect(reverse('blog_app:blog_list'))
            else:

                return render(request, 'login_app/error.html', context={"success": False})
        else:
            active = False
            return render(request, 'login_app/error.html', context={'success': False, 'active': False})

    else:

        signin = AuthenticationForm()

    dict = {'form': signin, 'success': success}
    return render(request, 'login_app/login.html', context=dict)


@login_required
def signOut(request):
    logout(request)
    messages.error(request, "You are Logged Out")
    # return render(request, 'blog_app/blog_list.html')
    return HttpResponseRedirect(reverse('blog_app:blog_list'))


def user_profile(request):
    current_user = request.user
    return render(request, 'login_app/profile.html')


@login_required
def user_info_change(request):
    current_user = request.user
    form = UserInfoChange(instance=current_user)
    if request.method == "POST":
        print("IN It")
        form = UserInfoChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/info_change.html', context={'form': form})


@login_required
def pass_change(request):
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method == "POST":
        form = PasswordChangeForm(current_user, request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login_app: '))
    return render(request, 'login_app/pass_change.html', context={'form': form})


@login_required
def add_pro_pic(request):
    form = ProfilePicForm()
    if request.method == "POST":
        form = ProfilePicForm(request.POST, request.FILES)
        if form.is_valid():
            user_info = form.save(commit=False)
            user_info.user = request.user
            user_info.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/add_pro_pic.html', context={'form': form})


@login_required
def change_pro_pic(request):
    form = ProfilePicForm(instance=request.user.user_profile)
    if request.method == "POST":
        form = ProfilePicForm(request.POST, request.FILES,
                              instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    return render(request, 'login_app/add_pro_pic.html', context={'form': form})

templates/login_app/add_pro_pic.html
{% extends 'base.html' %} {% block title %} Add Profile Picture {% endblock %}
{% block intro %}{% endblock %} {% block content %}
<form method="POST" enctype="multipart/form-data">
  {{ form }} {% csrf_token %}
  <button class="btn btn-success btn-sm">Add!</button>
</form>
{% endblock %}

templates/login_app/error.html
{% extends 'base.html' %}
<!-- sadadas -->
{% block title %} error{% endblock %} {% block intro %}{% endblock %}
<!-- dasdsadasd -->
{% block content %} {% if success is False %}

<h1 class="alert alert-danger">Wrong Username or Email.</h1>
<p class="lead alert alert-danger">Please Try Again</p>

{% elif active is False %}
<h1 class="alert alert-danger">Sorry,The User is not Active</h1>
<p class="lead">
  Go to
  <a href="{% url 'blog_app:blog_list' %}" class="text-primary"></a> HomePage
</p>
{% else %} {% for msg in messages %}
<h1 class="alert alert-danger">{{ msg }}</h1>
{% endfor %}
<p class="lead">
  Go to
  <a href="{% url 'blog_app:blog_list' %}" class="text-primary">HomePage</a>
</p>
{% endif %} {% endblock %}

templates/login_app/info_change.html
{% extends 'base.html' %}
<!-- dsadasd -->
{% load crispy_forms_tags %}
<!-- sadasd -->
{% block title %} Change Profile {% endblock %} {% block intro %}{% endblock %}
<!-- Main Content -->
{% block content %}

<form method="POST">
  {{ form|crispy }}
  <!--sdasdsa  -->
  {% csrf_token %}
  <input type="submit" value="Update" class="btn btn-primary btn-md" />
</form>

{% endblock %}

templates/login_app/login.html
{% extends 'base.html' %}
<!-- saasdasd -->
{% load crispy_forms_tags %}
<!-- sadasd -->
{% block intro %}{% endblock %}
{% block title %} Sign Up {% endblock %}
<!-- sadasd -->
{% block content %}

{% for msg in messages %}
<div class="alert alert-primary alert-dismissible" role="alert" id="liveAlert">
  <strong>Congrats!</strong> {{ msg }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<div style="width: 50vw" class="m-auto mt-4">
  <form method="POST">
    {% csrf_token %}
    <!-- {{ form|crispy }} {% csrf_token %}
    <input
      type="submit"
      name="submit"
      value="Sign In"
      class="btn btn-primary btn-md"
    />
  </form> -->
  {% for field in form %}
        <div class="form__field">
          <label class='form-labels' for="formInput#text">{{ field.label }}</label>
          {{ field }}
        </div>
  {% endfor %}

  <input type="submit" class="mt-2 btn btn-outline-primary" value="Sign in">

</div>

<div class="alert alert-warning w-50 m-auto p-3">
  Haven't Registerd Yet?
  <a href="{% url 'login_app:signup' %}" class="alert-link">Sign Up First</a>
</div>
{% endblock %}

templates/login_app/pass_change.html
{% extends 'base.html' %}
<!-- sdasdasd -->
{% load crispy_forms_tags %}
<!-- sadada -->
{% block title %} Change Profile {% endblock %} {% block intro %}{% endblock %}
<!-- Main Content -->
{% block content %}

<form method="POST">
  {{ form|crispy }}
  <!--sdasdsa  -->
  {% csrf_token %}
  <input type="submit" value="Update" class="btn btn-primary btn-md" />
</form>

{% endblock %}

templates/login_app/profile.html
{% extends 'base.html' %} {% block title %} Profile {% endblock %}
<!-- saasdsa -->
{% block intro %}{% endblock %}
<!-- sadasdasdas -->
{% block content %}
<h2>Your Profile:</h2>
<hr />
<p>Name: {{ user.first_name }} {{ user.last_name }}</p>
<p>Username: {{ user.username }}</p>
{% if user.user_profile %}
<img
  src="/media/{{ user.user_profile.profile_pic }}"
  alt="myImage"
  class="rounded-circle"
  width="200px"
/>
<a href="{% url 'login_app:change_pic' %}" class="btn btn-primary btn-sm"
  >Change Profile Pic</a
>
{% else %}
<img
  src="/media/profile_pics/default.jpeg"
  alt="defaultImage"
  class="rounded-circle"
  width="200px"
/>
<br />
<br />
<a href="{% url 'login_app:add_pic' %}" class="btn btn-primary btn-sm"
  >Add Profile Pic</a
>
{% endif %}
<p>Email: {{ user.email }}</p>
<a href="{% url 'login_app:change_info' %}" class="btn btn-warning btn-md"
  >Change Info</a
>

{% endblock %}

templates/login_app/register.html
{% extends 'base.html' %}
<!-- sadasda -->
{% load crispy_forms_tags %}
<!-- asdasd -->
{% block title %} Create A User {% endblock %} {% block intro %}{% endblock %}
<!-- sadsaasd -->
{% block content %} {% if registered %}
<div class="alert alert-success">
  Congratulation!!! Registration Succesfull.
  <a href="{% url 'login_app:signin' %}" class="alert-link">Login here</a>
</div>
{% else %}

<div style="width: 50vw" class="m-auto mt-4">
  <form method="POST">
    {{ form|crispy }} {% csrf_token %}
    <input
      type="submit"
      name="submit"
      value="Register"
      class="btn btn-outline-primary mt-3"
    />
  </form>
</div>

<div class="alert-info my-2 w-50 m-auto p-3">
  Already Registered?
  <a class="alert-link" href="{% url 'login_app:signin' %}">Login here</a>
</div>

{% endif %} {% endblock %}