blog_app/urls.py
from django.urls import path
from . import views

app_name = "blog_app"
# Contails all urls for the blog app

urlpatterns = [

    path('write/', views.CreateBlog.as_view(), name="write"),
    path('blog_list/', views.BlogList.as_view(), name="blog_list"),
    path('blog_details/<slug>', views.blog_details, name="blog_details"),
    path('my_blogs/', views.MyBlogs.as_view(), name="my_blogs"),
    path('edit_blogs/<int:pk>', views.UpdateBlogs.as_view(), name="edit_blogs"),
    path('liked/<int:pk>', views.liked_blog, name="like"),
    path('unliked/<int:pk>', views.unlike_blog, name="unlike"),
    path("search/", views.search, name="search")
     ]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('', views.home, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name = "login_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signUp, name="signup"),
    path('signin/', views.signIn, name="signin"),
    path('signout/', views.signOut, name='signout'),
    path('profile/', views.user_profile, name="profile"),
    path('change_info/', views.user_info_change, name="change_info"),
    path("password/", views.pass_change, name="pass_change"),
    path("add_pic/", views.add_pro_pic, name="add_pic"),
    path("change_pic/", views.change_pro_pic, name="change_pic"),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <style>
      #read {
        text-decoration: none;
        color: #cc062d;
        font-weight: 400;
        font-size: 0.9em;
      }
      #read:hover {
        text-decoration: underline;
      }
      ::selection {
        background-color: #fdfcfc;
      }
      #users {
        color: #4e02db;
      }
      #users:hover {
        color: #1900a8;
      }
      p {
        font-family: Reithsans, Arial, Helvetica, sans-serif;
        font-size: 20px;
      }
      #topic {
        font-family: "Times New Roman", serif;
        text-shadow: 0px 2px #d9ddde;
      }
      .background {
        background-color: #7a9cc6;
      }

      #about-btns{
background: none!important;
  border: none;
  padding: 8px 0px!important;
  font-weight:3px;
   color: #999495;
  cursor: pointer;
 }
 #about-btns:focus{
outline: none;
  box-shadow: none
 }
 #about-btns:hover{
 color:#bfc5c8;
 background-color: #5bc0de;
 outline: none;
  box-shadow: none
 }
  #about-btns:active{
   outline: none;
  box-shadow: none
  }
  .modal-content { background: #ffb66e !important;
   backgound-color:#7a9cc6 ;
   color: #2f343b}

    </style>
    <meta charset="utf-8" />
    <title>{% block title %} Blog {% endblock %}</title>
    <!-- popup link-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Bootstrap CSS links-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />
    <!-- Font Awesome -->
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'main.css' %}" />
  </head>
  <body>
    <main
      id="mains"
      style="background-color: #ffe; overflow: auto"
      class="min-vh-100"
    >
      {% include 'navBar.html' %} {% block intro %}

      {% endblock %}

      <div class="container mt-2 pt-2">
        {% block content %}
        <h1>I am Base Page</h1>
        {% endblock %}
      </div>
    </main>
    {% include 'footer.html' %}
    <!-- JQuery Library -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
      integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
      integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/footer.html
<footer class="text-center p-4 footer" style=" color:white; background-color:#343a40;">
    © 2021 Copyright
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/"></a>
  </footer>

templates/navBar.html
<!-- <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'home' %}">
        <h3>SHARE!</h3>
      </a>
    </li>
    {% if user.is_authenticated %}
    <div class="nav-item dropdown">
      <a
        class="nav-link dropdown-toggle"
        href="#"
        id="navbardrop"
        data-toggle="dropdown"
      >
        @{{user.username}}
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'blog_app:write' %}"
          >Write Blog</a
        >
        <a class="dropdown-item" href="{% url 'blog_app:my_blogs'  %} "
          >My Blogs</a
        >
        <a class="dropdown-item" href="{% url 'login_app:profile' %}"
          >Your Profile</a
        >
        <hr />
        <a class="dropdown-item" href="{% url 'login_app:signout' %}">Logout</a>
      </div>
    </div>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login_app:signup' %}">Sign Up</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login_app:signin' %}">Login</a>
    </li>
    {% endif %}
  </ul>
</nav> -->

<nav
  class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top"
  style="position: relative"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"
      ><img src="/media/pen.png" width="60px" alt="Something"
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item btn btn-outline-info dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ user.username }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'blog_app:write' %}"
                >Write Blog</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'blog_app:my_blogs'  %}"
                >My Blogs</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'login_app:profile' %}"
                >My Profile</a
              >
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'login_app:signout' %}"
                >Logout</a
              >
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'login_app:signup' %}"
            >Sign Up</a
          >
        </li>
        <li>
        <a class="nav-item link-btn">
          <a
            class="nav-link"
            href="{% url 'login_app:signin' %}"
            >Login</a
          >
        </a>
          </li>
        <li>
          <div class="container" >
          <button id="about-btns" type="button" class="btn btn-primary " data-toggle="modal" data-target="#myModal"> About
          </button>
          <!-- The Modal -->
  <div class="modal " id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Welcome Nsuers!!!</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <p>
            Bored of posting course and faculty reviews on Facebook ? Why not
            talk about things that fascinates you!! <br>

            This is a place where you can share your thoughts with your fellow
            NSUers by writing about things that you are interested in, also
            recieve feedback from them. Why not learn new things from here?
          </p>
        </div>
      </div>
    </div>
  </div>

</div>
        </li>

        {% endif %}
      </ul>
      <form method="GET" action="{% url 'blog_app:search' %}" class="d-flex">
        {% csrf_token %}
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="query"
        />
        <button class="btn btn-outline-info" type="submit">Search</button>
      </form>
      <a href="/admin" class="btn btn-outline-danger ms-2">Admin Panel</a>
    </div>
  </div>
</nav>